# Generated by Django 3.0.2 on 2020-01-31 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0a5a196e-ab34-435d-bb94-70f45fb07970'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('939a8489-bb90-4e6c-9eca-f6201e501253'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('053bd96c-ba5c-4d75-ab41-d56492622313'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('overviewImage', models.ImageField(upload_to='uploads/')),
                ('orderIndex', models.IntegerField(unique=True)),
                ('activityType', models.CharField(choices=[('html', 'HTML'), ('mcq', 'MCQ')], default='HTML', max_length=500)),
                ('html', models.ManyToManyField(to='programLibrary.HTML')),
                ('mcq', models.ManyToManyField(to='programLibrary.MCQ')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('79f4a60c-6568-4324-a8b6-97330d709c0f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('sections', models.ManyToManyField(to='programLibrary.Section')),
            ],
        ),
    ]
