# Generated by Django 3.0.2 on 2020-01-31 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ed28054-a8e1-4006-aefe-1e26c8b026bb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d8d78e2-aa09-494f-8326-6c83a940b4f4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a78c849-a078-4355-8684-4f7249573ea4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aaabe9f6-fe34-4da2-ae81-25c765252fde'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
