# Generated by Django 3.0.2 on 2020-02-02 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0002_auto_20200130_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09c8fca4-6de7-4109-a93d-771e34899b3c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('911fd607-08ac-48cd-9a8d-eca37e5bd5e7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a59925fb-1103-49d3-a03f-b178e26aef62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('181db60e-d1c6-423e-a4d9-7ded4de2fda1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
