# Generated by Django 3.0.2 on 2020-02-02 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0007_auto_20200201_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d68c919-e8c3-4dc5-8e2a-cb2a9497df00'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4456cf19-f712-4ba3-a5ce-5e626a130508'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fb87363-4461-4187-befe-e60f3b7f8ce6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dce47d2-595f-40bb-8c6e-2893c5bd8835'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
