# Generated by Django 3.0.2 on 2020-02-02 01:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0008_auto_20200201_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b229cccb-5067-4711-bc40-3af32ccdffc6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f8b6183-48b3-49aa-917d-4d7688255fcd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d8e53a85-b07c-4282-bd39-150d4a38b2cd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ad7d36a-6aa0-4079-98cf-c3e0a5cb22bd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
