# Generated by Django 3.0.2 on 2020-02-02 01:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0009_auto_20200201_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c064808-fe3b-4a72-86f0-3a7e09a5f933'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c12e98fe-a009-4bd2-a2ea-cc68917aaf5a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0573c46-94b6-4a82-aad1-ac7fbd62d3d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d867cc9-88eb-464f-b5d0-9e59b4d2c701'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
