# Generated by Django 3.0.2 on 2020-02-02 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0010_auto_20200201_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('871fc8cc-7ae4-4405-b751-eeeee9d5468a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0177732f-3f7d-4773-94e3-18ba92bd193d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78317bf1-897d-44a7-9ca8-04bb33a481db'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d240f753-a085-414d-a3de-ae7b81288873'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
