# Generated by Django 3.0.2 on 2020-02-02 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0011_auto_20200201_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64674d16-910a-42d5-8481-b8376b2c71aa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40a0545b-c135-4ba7-b22f-7276a7d9a621'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2383683b-d898-4230-b142-ce61440b3a5c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51ef2a4f-d4f5-4056-851b-df094bff95d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
