# Generated by Django 3.0.2 on 2020-02-02 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0012_auto_20200202_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html',
            name='content',
        ),
        migrations.AddField(
            model_name='html',
            name='encodedContent',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='mcq',
            name='optionFive',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mcq',
            name='optionFour',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mcq',
            name='optionOne',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mcq',
            name='optionThree',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mcq',
            name='optionTwo',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3e18390-4c18-4f63-afdd-39e7724ae3a3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19bef116-799d-4161-820d-4e27dd4b8f33'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dfcb938c-616c-43c5-a7ed-ed9b1779a094'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4698276f-36a8-48ac-ab5e-aa0b2ccef30b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
