# Generated by Django 3.0.2 on 2020-02-02 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0013_auto_20200202_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6170f854-d4ba-4c61-b3f9-b4de544f490a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0b38d73-ba54-4773-b41c-9b41f49d6515'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fc3891d-a663-4e05-98be-59b4464642e7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50eed604-31c3-42ce-b76f-1fd1c4e7efb0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
