# Generated by Django 3.0.2 on 2020-02-02 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0014_auto_20200202_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9d69591-f031-41b4-986c-e0c37dc2536a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5990a4cb-9701-4617-b7c3-0d01ce0d16cd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6eca077-6981-4182-abbe-614da6e15aa7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d829641b-d8f5-4b0b-bccc-d6bec7fda021'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
