# Generated by Django 3.0.2 on 2020-02-03 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0015_auto_20200202_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83796646-f5c3-4b5b-956d-72d8b0361881'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39efa2d8-0817-421b-88ff-7494925db18c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dae1464d-a01f-4529-b558-a17a8f134b56'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1980ca2f-0fcb-4a5e-8a96-49cb734c4067'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
